version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: lms-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Password@1
      MYSQL_DATABASE: lms_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - lms-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: lms:app
    container_name: lms-backend
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/lms_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Password@1
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    networks:
      - lms-network

volumes:
  mysql_data:

networks:
  lms-network:
    driver: bridge
