apiVersion: v1
kind: Service
metadata:
  name: lms-backend
  namespace: lms
spec:
  type: NodePort
  selector:
    app: lms-backend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
